"""empty message

Revision ID: 6d2c82564cc0
Revises: e4f6b1a9eef0
Create Date: 2025-05-25 14:13:30.814801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2c82564cc0'
down_revision = 'e4f6b1a9eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
