"""empty message

Revision ID: 9911a712cd17
Revises: fa02a7b03074
Create Date: 2025-05-15 19:25:06.678269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9911a712cd17'
down_revision = 'fa02a7b03074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('average_lifespan',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('average_height',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('average_height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
