"""empty message

Revision ID: fa02a7b03074
Revises: 0748a34fee6f
Create Date: 2025-05-15 15:53:00.273354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02a7b03074'
down_revision = '0748a34fee6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
